[package]
name = "doctor_finder"
version = "0.1.0"
authors = ["schneki <schneki.max@gmail.com>"]

[dependencies]
select = "0.4.2"
futures = "0.1"
hyper = "0.11"
hyper-tls = "0.1.3"
tokio-core = "0.1"
serde = ""
serde_json = ""
serde_derive = ""
csv = "1"
